version = 4.2.0
archive_dir = /etc/letsencrypt/archive/goldenblossom.ddns.net
cert = /etc/letsencrypt/live/goldenblossom.ddns.net/cert.pem
privkey = /etc/letsencrypt/live/goldenblossom.ddns.net/privkey.pem
chain = /etc/letsencrypt/live/goldenblossom.ddns.net/chain.pem
fullchain = /etc/letsencrypt/live/goldenblossom.ddns.net/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 6ef02e4bf17cd955295240d2559ea39a
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
goldenblossom.ddns.net = /var/www/html
