services:
  webserver:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: apache_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../www:/var/www/html
      - ../certs/etc:/etc/letsencrypt
    restart: unless-stopped

  database:
    image: mariadb:latest
    container_name: gbloom_db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: gbloom_db
      MYSQL_USER: gbloomer
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot_client
    entrypoint: ""
    volumes:
      - ../certs/etc:/etc/letsencrypt
      - ../www:/var/www/html
    command: 
      - certbot
      - certonly
      - --webroot
      - --webroot-path=/var/www/html
      - --email
      - tu-email@dominio.com
      - --agree-tos
      - --no-eff-email
      - -d
      - goldenblossom.ddns.net
